apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lightelligence-design-system
  labels:
    buildingBlock: {{ .Values.labels.buildingBlock }}
    component: {{ .Values.labels.component }}
  annotations:
    kubernetes.io/ingress.class: default
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /react
            backend:
              serviceName: lightelligence-design-system
              servicePort: 8080
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Values.cert.secretName }}
